# Generated by Django 6.0.2 on 2026-02-26 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("garmin_category", models.CharField(db_index=True, max_length=100)),
                ("garmin_name", models.CharField(db_index=True, max_length=200)),
                (
                    "muscle_group",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "equipment",
                    models.CharField(blank=True, default="Other", max_length=100),
                ),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("Strength", "Strength"),
                            ("Cardio", "Cardio"),
                            ("Stretch", "Stretch"),
                        ],
                        default="Strength",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "garmin_activity_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField(db_index=True)),
                ("sport", models.CharField(db_index=True, max_length=50)),
                ("duration_min", models.FloatField(blank=True, null=True)),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("calories", models.FloatField(blank=True, null=True)),
                ("avg_hr", models.FloatField(blank=True, null=True)),
                ("max_hr", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise", models.CharField(max_length=200)),
                (
                    "set_type",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Warmup", "Warmup"),
                            ("Rest", "Rest"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("reps", models.IntegerField(blank=True, null=True)),
                ("weight_kg", models.FloatField(blank=True, null=True)),
                ("duration_sec", models.FloatField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="fitness.workout",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
