# Generated by Django 6.0.2 on 2026-02-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("steps", models.IntegerField(blank=True, null=True)),
                ("total_calories", models.IntegerField(blank=True, null=True)),
                ("active_calories", models.IntegerField(blank=True, null=True)),
                ("resting_hr", models.IntegerField(blank=True, null=True)),
                ("avg_stress", models.IntegerField(blank=True, null=True)),
                ("body_battery_high", models.IntegerField(blank=True, null=True)),
                ("body_battery_low", models.IntegerField(blank=True, null=True)),
                ("sleep_hours", models.FloatField(blank=True, null=True)),
                ("hrv", models.FloatField(blank=True, null=True)),
                ("weight_kg", models.FloatField(blank=True, null=True)),
                ("vo2_max", models.FloatField(blank=True, null=True)),
                ("floors_climbed", models.IntegerField(blank=True, null=True)),
                ("intensity_minutes", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Daily stats",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("sets", models.IntegerField(default=3)),
                ("reps", models.IntegerField(default=10)),
                ("weight_kg", models.FloatField(blank=True, null=True)),
                ("rest_sec", models.IntegerField(default=90)),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                ("order", models.IntegerField(default=0)),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fitness.exercise",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="fitness.workouttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
