# Generated by Django 6.0.2 on 2026-02-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0002_dailystats_workouttemplate_templateexercise"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCheckin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                (
                    "mood",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="1 = very bad, 5 = great",
                        null=True,
                    ),
                ),
                (
                    "energy",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="1 = exhausted, 5 = energised",
                        null=True,
                    ),
                ),
                (
                    "stress",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "sleep_quality",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="1 = terrible, 5 = excellent",
                        null=True,
                    ),
                ),
                (
                    "sleep_hours_manual",
                    models.FloatField(
                        blank=True,
                        help_text="Only when Garmin not connected",
                        null=True,
                    ),
                ),
                ("hydration_litres", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "exercise_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Total exercise minutes (no Garmin)",
                        null=True,
                    ),
                ),
                (
                    "steps_estimate",
                    models.IntegerField(
                        blank=True, help_text="Estimated steps (no Garmin)", null=True
                    ),
                ),
                (
                    "exercise_description",
                    models.TextField(
                        blank=True, default="", help_text="What activity did you do?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="meals/%Y/%m/"),
                ),
                ("calories_est", models.IntegerField(blank=True, null=True)),
                ("protein_g", models.FloatField(blank=True, null=True)),
                ("carbs_g", models.FloatField(blank=True, null=True)),
                ("fat_g", models.FloatField(blank=True, null=True)),
                ("fiber_g", models.FloatField(blank=True, null=True)),
                (
                    "ai_analysis",
                    models.TextField(
                        blank=True, default="", help_text="Full AI response"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("", "Prefer not to say"),
                        ],
                        default="",
                        max_length=1,
                    ),
                ),
                ("height_cm", models.FloatField(blank=True, null=True)),
                ("weight_kg", models.FloatField(blank=True, null=True)),
                (
                    "profession",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "activity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sedentary", "Sedentary"),
                            ("light", "Lightly Active"),
                            ("moderate", "Moderately Active"),
                            ("active", "Very Active"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "health_conditions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Allergies, chronic conditions, medications, etc.",
                    ),
                ),
                (
                    "goals",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Weight loss, muscle gain, better sleep, etc.",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                ("garmin_connected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "User profile",
            },
        ),
    ]
