# Generated by Django 6.0.2 on 2026-02-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0003_dailycheckin_meal_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
