# Generated by Django 6.0.2 on 2026-02-27 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0004_images_to_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="workouttemplate",
            name="sport",
            field=models.CharField(
                choices=[
                    ("Strength Training", "Strength Training"),
                    ("Running", "Running"),
                    ("Cycling", "Cycling"),
                    ("Swimming", "Swimming"),
                    ("Walking", "Walking"),
                    ("Hiking", "Hiking"),
                    ("Yoga", "Yoga"),
                    ("Other", "Other"),
                ],
                default="Strength Training",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PlannedWorkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "time",
                    models.TimeField(
                        blank=True, help_text="Optional scheduled time", null=True
                    ),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("Strength Training", "Strength Training"),
                            ("Running", "Running"),
                            ("Cycling", "Cycling"),
                            ("Swimming", "Swimming"),
                            ("Walking", "Walking"),
                            ("Hiking", "Hiking"),
                            ("Yoga", "Yoga"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "duration_min",
                    models.IntegerField(
                        blank=True, help_text="Planned duration in minutes", null=True
                    ),
                ),
                (
                    "distance_km",
                    models.FloatField(
                        blank=True,
                        help_text="Planned distance (e.g. for Running)",
                        null=True,
                    ),
                ),
                ("garmin_synced", models.BooleanField(default=False)),
                (
                    "garmin_workout_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planned",
                        to="fitness.workouttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "time", "created_at"],
            },
        ),
    ]
